Terraform 0.12
lsst-sqre/terraform-tinfoil-tiller pull request #13
Opened 2019-08-14 15:01 UTC by seboudry

Hi!
Here's a TF 0.12 compliant version of this module :)

2019-08-14 15:41 UTC, seboudry commented
In order to the `pre-commit` test to pass, an upgrade of `lsstsqre/terraform-pre-commit` image with TF 0.12 is needed.
https://github.com/lsst-sqre/docker-terraform-pre-commit/blob/master/Dockerfile

2019-08-15 16:22 UTC, jhoblitt commented
I've added an image with tf 0.12.6.  The tag is `lsstsqre/terraform-pre-commit:tf-0.12.6`

https://github.com/lsst-sqre/docker-terraform-pre-commit/pull/2

2019-08-15 16:31 UTC, jhoblitt commented
@seboudry It looks like recent releases of `pre-commit-terraform` + tf 0.12.6 will still accept the 0.11 syntax without forcing a conversion?

2019-08-15 16:36 UTC, jhoblitt commented
FYI -- I'm low bandwidth today as I'm at a conference.  What do you think of `tf-0.12/0.10.x` as a release branch name?

2019-08-15 16:37 UTC, jhoblitt commented on main.tf
> +  metadata { # metadata
This should be a comment on the closing brace.

2019-08-15 16:38 UTC, jhoblitt requested changes
This looks good except for the odd relocation of the closing brace comments.

2019-08-16 13:08 UTC, seboudry commented on main.tf
> +  metadata { # metadata
Didn't see that. It's probably a `0.12upgrade` command impact.
But for me, we didn't need closing brace comments ;)

2019-08-16 13:29 UTC, seboudry commented
> I've added an image with tf 0.12.6. The tag is `lsstsqre/terraform-pre-commit:tf-0.12.6`
> 
> [lsst-sqre/docker-terraform-pre-commit#2](https://github.com/lsst-sqre/docker-terraform-pre-commit/pull/2)

Nice, the test passes with this new image. I'll push a new commit.

> @seboudry It looks like recent releases of `pre-commit-terraform` + tf 0.12.6 will still accept the 0.11 syntax without forcing a conversion?

I've tested `lsstsqre/terraform-pre-commit:tf-0.12.6` on current `0.10.x` branch:
- `pre-commit run -a` OK after auto modify `main.tf` by aligning closing brace comments (I'll remove them as they don't add value)

> FYI -- I'm low bandwidth today as I'm at a conference. What do you think of `tf-0.12/0.10.x` as a release branch name?

Why not have a `0.12.x` branch name? Did you follow TF versions on your versioning?

2019-08-28 13:28 UTC, seboudry commented
Hi @jhoblitt!
Sorry to bother you, any update on this PR?
Have a nice day

2019-12-17 09:47 UTC, seboudry commented
Hi @jhoblitt !
Any change for that PR to be merged? ;)

2020-08-17 07:53 UTC, kouk commented
@jhoblitt @afausti @athornton @digitizdat @rra is there any chance this will pass review and get merged? It would be great. kthxbye

2020-08-17 18:01 UTC, jhoblitt approved these changes

2020-08-17 18:04 UTC, jhoblitt commented
Yes, we can merge this but it can't go into the master branch as it will break tf 0.11. Note that this mod isn't necessary with helm v3 / terraform-provider-helm >= 1.0.0.

2020-08-17 18:12 UTC, jhoblitt commented
Merged into a branch named `tf-0.12/0.10.x`.

2020-08-17 18:12 UTC, closed without merging